version: '3.3'

services:
  jenkins:
    image: jenkins/jenkins:latest
#    environment:
#        - JENKINS_OPTS="--prefix=/jenkins"
    ports:
        - "8080:8080"
    volumes:
        - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:8.9-community
    depends_on:
        - postgresql
    environment:
        - sonar.jdbc.username=psql
        - sonar.jdbc.password=psql
        - sonar.jdbc.url=jdbc:postgresql://postgresql/sonar
        - sonar.login=sonar
        - sonar.password=ranos
        - sonar.telemetry.enable=false
    ports:
        - "9000:9000"
    volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs

  postgresql:
    image: postgres:12
    environment:
        - POSTGRES_USER=psql
        - POSTGRES_PASSWORD=psql
        - POSTGRES_DB=sonar
    volumes:
        - postgresql:/var/lib/postgresql
        - postgresql_data:/var/lib/postgresql/data

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: