version: '3.3'

services:
  jenkins:
    image: jenkins/jenkins:latest
#    environment:
#        - JENKINS_OPTS="--prefix=/jenkins"
    ports:
        - "8080:8080"
    volumes:
        - jenkins-home:/var/jenkins_home


volumes:
  jenkins-home: